# Week 2 Notes
## Lists and Arrays, Numpy, Matplotlib

Review the solution from last week.

In [3]:
def transpose(A):
    """
    (list of list) -> list of list
    Given a matrix A, return a new matrix which is the transpose of A.
    """
    # Empty list will be the outer list for our matrix.
    new_mat = []
    
    # Iterate through the number of columns 
    # (note that each row has same # columns so we use A[0])
    for j in range(len(A[0])):
        # Empty list to construct a row
        inner = []
        # Iterate through the rows of A
        for i in range(len(A)):
            # Append the jth element from each row to the matrix
            # We are going down the column appending the elements
            # These elements traversed down the column will now be a row
            inner.append(A[i][j])
            
        # Now append the inner list that has the column elements to the matrix
        # This is now a row and the matrix is transposed.
        new_mat.append(inner)
        
    return new_mat

Let's see how we can do last week's questions using Numpy. Numpy us very versatile and can greatly simplify many tasks scientists typically do with lists such as linear algebra.

In [4]:
# Import some packages
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

The most basic thing which we will use a lot is a numpy array. This is similar to a Python list but it is static (can't be made smaller or larger) and has built in operations for linear algebra. We declare an array as:

In [5]:
my_arr = np.array([1, 2, 3])

In [6]:
my_arr

array([1, 2, 3])

We can also declare matrices in numpy:

In [7]:
matrix = np.array([[1, 2], [3, 4]])

In [8]:
matrix

array([[1, 2],
       [3, 4]])

Notice that is conveniently prints it out nicely like a matrix now!

Let's do the problems from last week using Numpy. First let's look at all the functions that Numpy has available. We can do this in Jupyter using dir() or we can search the internet for the tech docs. Let's try it with dir().

In [ ]:
dir(np)

If we wanted to know more about one then we can find out more by using help()

In [ ]:
help(np.array)

Lot's of details here but the examples are quite useful. Let's try the questions from last week now: 

In [9]:
# Define 2 matrices and 2 vectors to use for the examples
a = np.array([1, 2])
b = np.array([5, 6])

A = np.array([[1, 2], [3, 2]])
B = np.array([[3, 4], [1, 2]])

In [10]:
# 1. Dot product
a.dot(b)

17

In [11]:
# 2. Matrix by vector
A.dot(a)

array([5, 7])

In [12]:
# 3. Transpose
A.T

array([[1, 3],
       [2, 2]])

In [13]:
# 4. Multiply Matrices
# 2 Ways:
# (1).
A.dot(B)

array([[ 5,  8],
       [11, 16]])

In [14]:
# (2).
A @ B

array([[ 5,  8],
       [11, 16]])

In [15]:
# 5. Matrix x Matrix x Vector
(A @ B).dot(a)

array([21, 43])

Let's do a different example that uses what we learned last week, a numpy array and one more new feature. We will talk about the if statement and how we can use it for conditional flow control. The general form is:

```Python
if condition:
    # Code to run
elif condition2:
    # Code to run instead
else:
    # If neither 1 nor 2 are true
```

The conditions take the form of boolean expressions. They use the operators: <, >,<=, >=, ==, !=, and, or. Let's do a simple example:

In [ ]:
n = 6

if n > 6:
    print("Bigger than 6")
else:ww
    print("Smaller than 6")

In [ ]:
# Adding an elif

if n > 6:
    print("Bigger than 6")
elif n == 6:
    print("N equals 6")
else:
    print("Smaller than 6")
    

Now we will try using this to write a function to sort a numpy array. We will just use a simple selection sort algorithm. It is not the most efficient (scales $O(n^2)$) but for most purposes it is fine and it is much simpler to code than more advanced algorithms. One other new concept we will introduce here is mutability. Lists are mutable so we can actually edit the list (or array) using a function. This allows us to do things without making a new copy.

In [ ]:
def selection_sort(lst):
    # Iterate through the lst
    for i in range(len(lst)):
        # Keep track of the current smallest
        small = lst[i]
        small_ind = i
        
        # Look to see if there is a smaller item to the right
        for j in range(i + 1, len(lst)):
            if lst[j] < small:
                # If there is smaller item, update small
                small = lst[j]
                small_ind = j
                
        # Make a swap. Notice that if small doesn't change then this does nothing
        lst[small_ind] = lst[i]
        lst[i] = small
        
        
a = np.array([10, 7, 22, 1, 5])
selection_sort(a)
a

## Equations: solving and plotting

Let's start by making a simple equation solver. This will use a root finding method. The idea is that we have an equation of the form $F(x) = 0$ and we want to find where it intercepts the of the equation with the  axis on some interval. If we know the eqaution crosses this point on [a, b] and that it is continuous, then this is guaranteed to find a root (not all of them though) as long as sign(f(a)) /= sign(f(b)). Let's work through how we do this.

We will use: 

$$ 2 = x^2 \implies x^2 - 2 = 0 \implies F(x) = x^2 - 2$$

In [ ]:
# First define the function we want to solve
def F(x):
    return x**2 - 2

# Now The root finding method
def bisection(interval, func):
    a, b = interval
    
    middle = (a + b) / 2
    
    f_a = func(a)
    f_b = func(b)
    f_mid = func(middle)
    
    if f_mid < 0 and f_a > 0:
        return [a, middle]
    elif f_mid < 0 and f_a < 0:
        return [b, middle]
    elif f_mid > 0 and f_a > 0:
        return [middle, b]
    else:
        return [middle, a]
    

# Now we will test this. Let's try running it using 
# it's own previous result for 10 iteration first.
N = 40
a, b = [0, 5]
for i in range(N):
    a, b = bisection([a, b], F)
    
# If it converged, the two points should be close, let's see:
print(a, b)

# And the acutal value is:
print(np.sqrt(2))

Let's learn how to use Matplotlib while also seeing what is happening graphically. We will plot F(x) for this.

In [ ]:
# Prepare the x values
x = np.linspace(-5, 5, 100)
y = F(x)

fig, ax = plt.subplots()
ax.plot(x, y)
ax.set(title='An example plot', xlabel='X', ylabel='Y', ylim=(-3, 10), xlim=(-4, 4))
ax.plot(np.sqrt(2), 0, 'rx')
ax.grid()

# And if we want to save it:
fig.savefig('sample_plot.pdf')